apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n6oyr00u6-nodejs
  janus-idp.io/tekton: n6oyr00u6-nodejs
  backstage.io/kubernetes-id: n6oyr00u6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n6oyr00u6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
